STM32F4_HAL_LIB = $(LIB_DIR)/STM32F4xx_HAL_Driver

VPATH += $(STM32F4_HAL_LIB)/Src/
INCLUDES += -I$(STM32F4_HAL_LIB)/Inc

LIB_OBJ += stm32f4xx_hal.o
# LIB_OBJ += stm32f4xx_hal_adc.o
# LIB_OBJ += stm32f4xx_hal_adc_ex.o
# LIB_OBJ += stm32f4xx_hal_can.o
# LIB_OBJ += stm32f4xx_hal_cec.o
LIB_OBJ += stm32f4xx_hal_cortex.o
LIB_OBJ += stm32f4xx_hal_crc.o
# LIB_OBJ += stm32f4xx_hal_cryp.o
# LIB_OBJ += stm32f4xx_hal_cryp_ex.o
# LIB_OBJ += stm32f4xx_hal_dac.o
# LIB_OBJ += stm32f4xx_hal_dac_ex.o
# LIB_OBJ += stm32f4xx_hal_dcmi.o
# LIB_OBJ += stm32f4xx_hal_dcmi_ex.o
# LIB_OBJ += stm32f4xx_hal_dfsdm.o
# LIB_OBJ += stm32f4xx_hal_dma.o
# LIB_OBJ += stm32f4xx_hal_dma2d.o
# LIB_OBJ += stm32f4xx_hal_dma_ex.o
# LIB_OBJ += stm32f4xx_hal_dsi.o
# LIB_OBJ += stm32f4xx_hal_eth.o
# LIB_OBJ += stm32f4xx_hal_exti.o
LIB_OBJ += stm32f4xx_hal_flash.o
LIB_OBJ += stm32f4xx_hal_flash_ex.o
LIB_OBJ += stm32f4xx_hal_flash_ramfunc.o
# LIB_OBJ += stm32f4xx_hal_fmpi2c.o
# LIB_OBJ += stm32f4xx_hal_fmpi2c_ex.o
# LIB_OBJ += stm32f4xx_hal_gpio.o
# LIB_OBJ += stm32f4xx_hal_hash.o
# LIB_OBJ += stm32f4xx_hal_hash_ex.o
# LIB_OBJ += stm32f4xx_hal_hcd.o
# LIB_OBJ += stm32f4xx_hal_i2c.o
# LIB_OBJ += stm32f4xx_hal_i2c_ex.o
# LIB_OBJ += stm32f4xx_hal_i2s.o
# LIB_OBJ += stm32f4xx_hal_i2s_ex.o
# LIB_OBJ += stm32f4xx_hal_irda.o
# LIB_OBJ += stm32f4xx_hal_iwdg.o
# LIB_OBJ += stm32f4xx_hal_lptim.o
# LIB_OBJ += stm32f4xx_hal_ltdc.o
# LIB_OBJ += stm32f4xx_hal_ltdc_ex.o
# LIB_OBJ += stm32f4xx_hal_mmc.o
# LIB_OBJ += stm32f4xx_hal_nand.o
# LIB_OBJ += stm32f4xx_hal_nor.o
# LIB_OBJ += stm32f4xx_hal_pccard.o
# LIB_OBJ += stm32f4xx_hal_pcd.o
# LIB_OBJ += stm32f4xx_hal_pcd_ex.o
LIB_OBJ += stm32f4xx_hal_pwr.o
LIB_OBJ += stm32f4xx_hal_pwr_ex.o
# LIB_OBJ += stm32f4xx_hal_qspi.o
LIB_OBJ += stm32f4xx_hal_rcc.o
LIB_OBJ += stm32f4xx_hal_rcc_ex.o
# LIB_OBJ += stm32f4xx_hal_rng.o
# LIB_OBJ += stm32f4xx_hal_rtc.o
# LIB_OBJ += stm32f4xx_hal_rtc_ex.o
# LIB_OBJ += stm32f4xx_hal_sai.o
# LIB_OBJ += stm32f4xx_hal_sai_ex.o
# LIB_OBJ += stm32f4xx_hal_sd.o
# LIB_OBJ += stm32f4xx_hal_sdram.o
# LIB_OBJ += stm32f4xx_hal_smartcard.o
# LIB_OBJ += stm32f4xx_hal_smbus.o
# LIB_OBJ += stm32f4xx_hal_spdifrx.o
# LIB_OBJ += stm32f4xx_hal_spi.o
# LIB_OBJ += stm32f4xx_hal_sram.o
# LIB_OBJ += stm32f4xx_hal_tim.o
# LIB_OBJ += stm32f4xx_hal_tim_ex.o
# LIB_OBJ += stm32f4xx_hal_uart.o
# LIB_OBJ += stm32f4xx_hal_usart.o
# LIB_OBJ += stm32f4xx_hal_wwdg.o
LIB_OBJ += stm32f4xx_ll_adc.o
LIB_OBJ += stm32f4xx_ll_crc.o
LIB_OBJ += stm32f4xx_ll_dac.o
LIB_OBJ += stm32f4xx_ll_dma.o
LIB_OBJ += stm32f4xx_ll_dma2d.o
LIB_OBJ += stm32f4xx_ll_exti.o
# LIB_OBJ += stm32f4xx_ll_fmc.o
# LIB_OBJ += stm32f4xx_ll_fsmc.o
LIB_OBJ += stm32f4xx_ll_gpio.o
LIB_OBJ += stm32f4xx_ll_i2c.o
LIB_OBJ += stm32f4xx_ll_lptim.o
LIB_OBJ += stm32f4xx_ll_pwr.o
LIB_OBJ += stm32f4xx_ll_rcc.o
LIB_OBJ += stm32f4xx_ll_rng.o
LIB_OBJ += stm32f4xx_ll_rtc.o
# LIB_OBJ += stm32f4xx_ll_sdmmc.o
LIB_OBJ += stm32f4xx_ll_spi.o
LIB_OBJ += stm32f4xx_ll_tim.o
LIB_OBJ += stm32f4xx_ll_usart.o
# LIB_OBJ += stm32f4xx_ll_usb.o
LIB_OBJ += stm32f4xx_ll_utils.o

# LIB_OBJ += stm32f4xx_hal_msp_template.o
# LIB_OBJ += stm32f4xx_hal_timebase_rtc_alarm_template.o
# LIB_OBJ += stm32f4xx_hal_timebase_rtc_wakeup_template.o
# LIB_OBJ += stm32f4xx_hal_timebase_tim_template.o
